Feature/kenneth salt/renderhtml
BenGardiner/mindmup-as-attack-trees pull request #18
Opened 2017-12-06 16:58 UTC by kennethblite

rendermup.js has been replaced by render_mup.js, running it will produce the desired files, added webstub.html that allows inlining of all dependencies.

2017-12-07 15:27 UTC, BenGardiner requested changes

2017-12-07 15:27 UTC, BenGardiner commented on scripts/checks.py
> +normalize_nodes(root_node)
looks like your checks.py changes crept in to this MR.

2017-12-07 15:27 UTC, BenGardiner commented on scripts/webstub.html
> +%%jsondata%%
ok awesome!

Is there a command-line to do the substitution into this file?

2017-12-13 18:29 UTC, BenGardiner approved these changes

2017-12-18 21:01 UTC, kennethblite commented
@BenGardiner Do you want me to merge?

2017-12-19 16:31 UTC, BenGardiner commented
@kennethblite 

This branch now contains everything in #15 also. I've tweaked your render_mup.js. It just does HTML output, rendermup (old) still does png files.

I'd like to open an issue to track the 'fork' between the two scripts. But otherwise this is ready to merge. And thank you again. The work you did here to get us over the hump of creating standalone HTML files has greatly improved the browsing experience of the trees.

2017-12-19 18:40 UTC, merged